Fix: Fatal error: During inheritance of ArrayAccess in PHP 8.1
tipee-sa/slim-2.x pull request #1
Opened 2022-05-06 09:44 UTC by louislam

Problem:

For PHP 8.1, if `error_reporting` set to `E_ALL`, it will throw exception like this:

```
Fatal error: During inheritance of ArrayAccess: Uncaught ErrorException: 

Return type of Slim\Http\Response::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/gammadia/slim-2.x/Slim/Http/Response.php:451
```

This pull request:

Add missing return types to all related methods in order to solve the issue.

2022-05-06 10:06 UTC, louislam commented
Btw, thanks for extending the life of Slim 2. I love Slim 2 very much. It is very simple to use and I love to `echo` as the response.

While starting from Slim 3, they chose to stick with PSR request/response, things no longer straightforward and it became more like express.js.

And I just checked the [example](https://www.slimframework.com/docs/v4/) of Slim 4, it is not slim anymore... Just like a Java program with many unnecessary design patterns.

2022-06-15 12:13 UTC, FilipBenco commented
great work @louislam! @gnutix Is there any way we can help here, to get this PR get merged as soon as possible?

2022-06-15 12:45 UTC, gnutix requested changes
Thanks for your contribution @louislam ! Sorry I didn't saw it any sooner, it's the first time someone (outside our company) contributes to one of our packages, AFAIK. :wink:

There's two small review comments, would you mind fixing them ? :pray:

2022-06-15 12:45 UTC, gnutix commented on Slim/Http/Response.php
> +    public function isServerError(): bool
```suggestion
    public function isServerError()
```

This one is not necessary for PHP 8.1 compatibility (so I'd rather have it remain as it is).

2022-06-15 12:45 UTC, gnutix commented on Slim/Http/Response.php
> +    public function offsetExists($offset) : bool
```suggestion
    public function offsetExists($offset): bool
```

Extra space.

2022-06-15 12:59 UTC, louislam commented on Slim/Http/Response.php
> +    public function offsetExists($offset) : bool
Thanks, fixed.

2022-06-15 13:01 UTC, merged

2022-06-15 13:04 UTC, gnutix commented
Hmm.. I merged a little fast. Don't know why, but Github Actions had not run on this PR, and it's red. I'll fix it separately, then tag a new release once it's green.

2022-06-15 13:15 UTC, louislam commented on Slim/Http/Response.php
>       * @return \Slim\Http\Headers
phpstan complains about this, I think phpdoc's @return have to match the actual data type.

2022-06-15 13:20 UTC, gnutix commented on Slim/Http/Response.php
>       * @return \Slim\Http\Headers
Indeed. And we cannot use `mixed` because of PHP 7.x support, see https://github.com/gammadia/slim-2.x/pull/3/files.

2022-06-15 13:26 UTC, gnutix commented
@louislam @FilipBenco A new `2.6.3` (#0a08bb1) tag was pushed. You can run `composer update gammadia/slim-2.x` and it should be good.

2022-06-15 13:27 UTC, FilipBenco commented
guys, you re the best! thank you a lot :)